project_name: Nengo Interface
pkg_name: nengo_interfaces
repo_name: nengo/nengo-interfaces

description: Simplified external input and output communication
copyright_start: 2020
license: abr-free

main_branch: main

license_rst: {}

contributing_rst: {}

contributors_rst: {}

setup_py:
  install_req:
    - nengo>=3.0.0
  tests_req:
    - pytest>=4.3.0
  classifiers:
    - "Development Status :: 5 - Alpha"
    - "Framework :: Nengo"
    - "Intended Audience :: Science/Research"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python "
    - "Programming Language :: Python :: 3.8"
    - "Topic :: Scientific/Engineering "
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

setup_cfg:
  pylint:
    ignore:
      - _vendor
      - compat.py
      - nengo/spa
    disable:
      - missing-module-docstring

ci_scripts:
  - template: static

pre_commit_config_yaml: {}

pyproject_toml: {}
